# Generated by Django 4.2.14 on 2024-07-16 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='resourcetitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='resourceurl',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='mood',
            field=models.IntegerField(choices=[(1, 'happy'), (2, 'neutral'), (3, 'sad')], default=2),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
