# Generated by Django 4.2.14 on 2024-07-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_resource_creation_date_remove_resource_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
