# Generated by Django 4.2.14 on 2024-07-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_resource_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
